// master-list.js — Via/Device/Item 표준 목록 (리스트.xlsx 기준, 자동 생성)
// 이 파일의 배열은 CSC/거래처이력/카트리지기록 등 신규 입력 시 '목록에서만 선택' 강제를 위한 기준 데이터입니다.
// 목록을 늘리거나 수정해야 하면 이 배열에 직접 추가/수정하세요 (원본 리스트.xlsx와 동기화 유지 권장).

var MASTER_VIA = [
  "email",
  "phone call",
  "SNS",
  "CSC(고객지원센터)",
  "Visit",
  "AFIAS NET",
  "QR Code",
  "Inquiry2",
  "Inquiry3"
];

var MASTER_DEVICE = [
  "AFIAS-1",
  "AFIAS-3",
  "AFIAS-6",
  "AFIAS-10",
  "AFIAS-50",
  "ichroma",
  "ichroma 2",
  "ichroma M2",
  "ichroma M3",
  "ichroma 3",
  "ichroma 3 Neo",
  "ichroma 10",
  "ichroma 50",
  "QDX-instacheck",
  "QDX-instacheck 2",
  "ichroma D reader",
  "ichroma SMART",
  "ichroma Duo reader",
  "ichamber",
  "Hemochroma 2",
  "Hemochroma plus",
  "EZ POC",
  "VETchroma",
  "TRIAS 1",
  "TRIAS 3",
  "NuActor",
  "ExAmplar",
  "ALCIS 1",
  "ALCIS 2",
  "Chemichroma",
  "CBChroma",
  "AFIAS V1",
  "ichroma 50 Plus"
];

var MASTER_ITEM = [
  "ichroma system check cartridge",
  "ichroma 3 system check cartridge",
  "AFIAS system check cartridge",
  "EZ POC system check cartridge",
  "VETchroma system check cartridge",
  "AFIAS washing cartridge",
  "AFP",
  "Adalimumab",
  "Adeno",
  "AFP Plus",
  "AMH",
  "Anti-CCP",
  "Anti-CCP Plus",
  "Anti-Golimumab",
  "Anti-HBs",
  "Anti-HCV",
  "ASO",
  "AST",
  "B-HCG",
  "b-hCG Plus",
  "BNP",
  "CA15-3",
  "CA125",
  "CA19-9",
  "Calprotectin",
  "Canine 3D",
  "Cardiac Triple",
  "cCRP",
  "CDV Ag",
  "CDV IgG/IgM",
  "CEA",
  "CEA Neo",
  "CEA Plus",
  "CK-MB",
  "CK-MB Neo",
  "CMV IgG",
  "CMV IgM",
  "cNT-proBNP",
  "Cortisol",
  "COVID-19 Ab",
  "COVID-19 Ag",
  "COVID-19 Ag Plus",
  "COVID-19 nAb",
  "COVID-19 PCR 3-gene",
  "COVID-19 PCR 3-gene Lyo",
  "COVID-19 real-time PCR kit(L)",
  "COVID-19 SP/NP IgG",
  "COVID-19/Flu Ag Combo",
  "cPL",
  "CPSE",
  "CPV IgG/IgM",
  "CRP",
  "CRP Neo",
  "Cyfra21-1",
  "Cystatin C",
  "D-Dimer",
  "D-Dimer Neo",
  "Dengue IgG/IgM",
  "Dengue NS1 Ag",
  "Estradiol",
  "Etanercept",
  "ExAmplar HBV viral load Lyo kit",
  "ExAmplar HCV viral load Lyo kit",
  "Feline 3D",
  "Ferritin",
  "Flu A+B",
  "fNT-rpoBNP",
  "fPL",
  "F-QC",
  "Free Anti-Adalimumab",
  "Free Anti-infliximab",
  "Free Anti-Trastuzumab",
  "Free PSA",
  "Free T4",
  "fSAA",
  "FSH",
  "FSH Plus",
  "Helicobacter SA",
  "H. pylori SA",
  "HbA1c",
  "HbA1c Neo",
  "HBsAg",
  "Hemochroma plus",
  "HIV",
  "hsCRP",
  "hsCRP All in one",
  "iFob Neo",
  "IGRA-TB",
  "IL-6",
  "Infliximab",
  "InfluA/B SARS-CoV-2 PCR Kit",
  "influenza A+B",
  "Influenza A+B/RSV",
  "Insulin",
  "KL-6",
  "LDL cholesterol Direct",
  "LH",
  "LH Plus",
  "mAMP/COC/THC",
  "Micro CRP",
  "Microalbumin",
  "Microcuvettes",
  "MxA/CRP",
  "Mycoplasma",
  "Myoglobin",
  "Noro",
  "NT-proBNP",
  "PCT",
  "PCT Plus",
  "PCT Plus G",
  "PRL",
  "PRL Plus",
  "Progesterone",
  "PSA",
  "PSA Neo",
  "PSA Plus",
  "PTH",
  "penKid",
  "Quick COVID-19 Ag",
  "RF IgM",
  "Rota",
  "Rota/Adeno",
  "RSV",
  "Rubella IgG",
  "Rubella IgM",
  "SAA",
  "SDMA",
  "Sputum DNA extraction kit",
  "ST2",
  "Strep A",
  "T3",
  "T4",
  "Testosterone",
  "Tn-I",
  "Tn-I Plus",
  "TN-T",
  "ToRC IgG",
  "Total Anti-infliximab",
  "Total B-hcG",
  "Total IgE",
  "Toxo IgG/IgM",
  "Toxo IgG",
  "T-QC",
  "TSH",
  "TSH Plus",
  "Ustekinumab",
  "vAFP",
  "vCortisol",
  "vD-dimer",
  "Vedolizumab",
  "vHelicobacter SA",
  "Viral DNA extraction kit",
  "CHIKV IgG/IgM",
  "Viral RNA extraction kit",
  "Vitamin D",
  "Vitamin D Neo",
  "vProgesterone",
  "vT4",
  "vTn-I",
  "General 19",
  "Electrolyte 7",
  "Liver and Kidney 11",
  "Glucose and Lipid 6",
  "vTSH",
  "AMP/EDDP/OPI",
  "BAR/BZO/TCA",
  "Carba 5",
  "Zika IgG/IgM"
];

// 알려진 오타/구표기 → 표준 표기 매핑 (기존 데이터에서 자주 보이는 변형 표기를 자동 교정하기 위함)
// 대소문자/공백 차이는 이미 자동 교정되므로, 여기에는 "다른 글자"로 된 변형만 등록하면 됩니다.
var MASTER_ALIASES = {
  "ALCIS I": "ALCIS 1",
  "ALCIS II": "ALCIS 2",
  "TRIAS-1": "TRIAS 1",
  "TRIAS-3": "TRIAS 3",
  "AFIAS-11": "AFIAS-10"
};
